openapi: 3.0.0
info:
  title: Water Testing API
  version: 1.0.0
  description: API for recording water tests, viewing history, and analyzing trends

paths:
  /api/aquariums/{aquariumId}/water-tests:
    get:
      summary: Get water test history for an aquarium
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
          description: Filter tests after this date
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
          description: Filter tests before this date
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
      responses:
        200:
          description: List of water tests
          content:
            application/json:
              schema:
                type: object
                properties:
                  tests:
                    type: array
                    items:
                      $ref: '#/components/schemas/WaterTest'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        401:
          description: Unauthorized

    post:
      summary: Record a new water test (manual entry)
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWaterTestInput'
      responses:
        201:
          description: Water test recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterTestResult'
        400:
          description: Validation error
        401:
          description: Unauthorized

  /api/aquariums/{aquariumId}/water-tests/{testId}:
    get:
      summary: Get a specific water test with recommendations
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
        - name: testId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Water test details with recommendations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterTestResult'
        404:
          description: Test not found
        401:
          description: Unauthorized

    patch:
      summary: Update water test notes
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
        - name: testId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notes:
                  type: string
      responses:
        200:
          description: Notes updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaterTest'
        404:
          description: Test not found
        401:
          description: Unauthorized

    delete:
      summary: Delete a water test
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
        - name: testId
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Test deleted
        404:
          description: Test not found
        401:
          description: Unauthorized

  /api/aquariums/{aquariumId}/water-tests/trends:
    get:
      summary: Get parameter trends over time
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
        - name: parameters
          in: query
          required: true
          schema:
            type: string
          description: Comma-separated parameter names (e.g., "ph,ammonia,nitrate")
        - name: days
          in: query
          schema:
            type: integer
            default: 30
          description: Number of days to look back
      responses:
        200:
          description: Trend data for requested parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrendData'
        401:
          description: Unauthorized

  /api/aquariums/{aquariumId}/water-tests/analyze-image:
    post:
      summary: Analyze a test strip image with AI (Genkit flow)
      tags: [WaterTests]
      security:
        - supabaseAuth: []
      parameters:
        - name: aquariumId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
                - stripBrand
              properties:
                image:
                  type: string
                  format: binary
                  description: Test strip image (JPEG, PNG, WEBP)
                stripBrand:
                  type: string
                  description: Brand of test strip (e.g., "API", "Tetra", "Seachem")
      responses:
        200:
          description: Analysis complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestStripAnalysisResult'
        400:
          description: Invalid image or unsupported strip brand
        401:
          description: Unauthorized
        500:
          description: AI analysis failed

components:
  securitySchemes:
    supabaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    WaterTest:
      type: object
      properties:
        id:
          type: string
        aquariumId:
          type: string
        testDate:
          type: string
          format: date-time
        parameters:
          type: object
          properties:
            ph:
              $ref: '#/components/schemas/ParameterReading'
            ammonia:
              $ref: '#/components/schemas/ParameterReading'
            nitrite:
              $ref: '#/components/schemas/ParameterReading'
            nitrate:
              $ref: '#/components/schemas/ParameterReading'
            kh:
              $ref: '#/components/schemas/ParameterReading'
            gh:
              $ref: '#/components/schemas/ParameterReading'
            chlorine:
              $ref: '#/components/schemas/ParameterReading'
            temperature:
              $ref: '#/components/schemas/ParameterReading'
        imageUrl:
          type: string
        stripBrand:
          type: string
        entryMethod:
          type: string
          enum: [ai, manual]
        overallConfidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
        notes:
          type: string
        hasWarnings:
          type: boolean
        hasCritical:
          type: boolean
        createdAt:
          type: string
          format: date-time

    ParameterReading:
      type: object
      properties:
        value:
          type: number
          format: float
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: AI confidence score (0-1)

    CreateWaterTestInput:
      type: object
      required:
        - parameters
      properties:
        testDate:
          type: string
          format: date-time
        parameters:
          type: object
          properties:
            ph:
              type: number
              format: float
            ammonia:
              type: number
              format: float
            nitrite:
              type: number
              format: float
            nitrate:
              type: number
              format: float
            kh:
              type: number
              format: float
            gh:
              type: number
              format: float
            chlorine:
              type: number
              format: float
            temperature:
              type: number
              format: float
        notes:
          type: string

    WaterTestResult:
      allOf:
        - $ref: '#/components/schemas/WaterTest'
        - type: object
          properties:
            recommendations:
              type: array
              items:
                $ref: '#/components/schemas/TreatmentRecommendation'

    TreatmentRecommendation:
      type: object
      properties:
        id:
          type: string
        waterTestId:
          type: string
        parameter:
          type: string
        issue:
          type: string
        severity:
          type: string
          enum: [warning, critical]
        productName:
          type: string
        productType:
          type: string
        dosageCalculation:
          type: string
        instructions:
          type: string
        safetyWarnings:
          type: array
          items:
            type: string
        compatibilityNotes:
          type: string
        purchaseLinks:
          type: array
          items:
            type: object
            properties:
              vendor:
                type: string
              url:
                type: string
              price:
                type: string
        priority:
          type: integer
          minimum: 1
          maximum: 5
        createdAt:
          type: string
          format: date-time

    TestStripAnalysisResult:
      type: object
      properties:
        waterTest:
          $ref: '#/components/schemas/WaterTest'
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/TreatmentRecommendation'
        analysisMetadata:
          type: object
          properties:
            modelUsed:
              type: string
            processingTimeMs:
              type: integer
            colorCalibrationScore:
              type: number
              format: float

    TrendData:
      type: object
      properties:
        aquariumId:
          type: string
        parameters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              unit:
                type: string
              optimalRange:
                type: object
                properties:
                  min:
                    type: number
                  max:
                    type: number
              dataPoints:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date-time
                    value:
                      type: number
                      format: float
                    confidence:
                      type: number
                      format: float

    Pagination:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        hasMore:
          type: boolean
